server:
  port: 8097
key:
  value:
    map:
      success: Sussefully done work
      error: Check sometthing Wrong 
      fail: Fail to do operation
    custromerlist:
    - kamal
    - raman
    - dharuv
    - madhup
    - rishab
    